{% set name = "orocos-kdl" %}
{% set version = "1.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/orocos/orocos_kinematics_dynamics/archive/v{{ version }}.tar.gz
  sha256: 6d4b04c465f0974286fbb419c40e3aca145f616571f2462e2696b830288234a9
  patches:
    - orocos_kdl.patch
    - python_orocos_kdl.patch
    - python_osx.patch                    # [osx]
    - assignment_operator.patch           # [unix]
    - crosscompile_sip_include_dir.patch  # [build_platform != target_platform]

build:
  number: 0
  skip: true  # [win and vc<14]
  script: echo 'do nothing'  # [unix]
  run_exports:
    - {{ pin_subpackage('orocos-kdl', max_pin='x.x') }}
    - {{ pin_subpackage('python-orocos-kdl', max_pin='x.x') }}

outputs:
  - name: orocos-kdl
    version: {{ version }}
    script: buildpkg.sh  # [unix]
    script: bldpkg.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - ninja       # [win]
        - make        # [not win]
        - pkg-config
      host:
        - eigen
      run:
        - eigen
    test:
      commands:
        - if not exist %LIBRARY_PREFIX%\\lib\\orocos-kdl.lib exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\lib\\orocos-kdl.dll exit 1  # [win]
        - test -f $PREFIX/lib/liborocos-kdl${SHLIB_EXT}              # [unix]
  - name: python-orocos-kdl
    version: {{ version }}
    script: buildpkg.sh  # [unix]
    script: bldpkg.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - ninja  # [win]
        - make  # [not win]
        - pkg-config
        - sip                                    # [build_platform != target_platform]
      host:
        - python
        - eigen
        - orocos-kdl
        - sip 4.19.20                            # [win]
        - sip                                    # [not win and build_platform == target_platform]
      run:
        - python
        - eigen
        - orocos-kdl
        - sip 4.19.20                            # [win]
        - sip                                    # [not win]
    test:
      imports:
        - PyKDL

about:
  home: https://github.com/orocos/orocos_kinematics_dynamics
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: orocos_kdl/COPYING
  summary: |
    Orocos Kinematics and Dynamics C++ library

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
